### PR TITLE
Travis CI: Upgrade to Python 3.8

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
@mekarpeles @tfmorris Your reviews please.

**Comment by tfmorris** [comment]
The Python 3.8 CI tests pass, so I'm satisfied with that piece. My only question is whether we should be testing Python 3.7 & 3.8 or just 3.8. Since 3.8 was just released it'd be fairly aggressive to use it in production, but I don't think we're actually looking at using Python 3.x for a while, so 3.8 only may be fine.

**Comment by cclauss** [comment]
Our test case is merely to run flake8 so I don't think the minor version matters much but Python 3.8 is a bit more strict that Python 3.7 in that it raises SyntaxWarnings on `x is y` when they should be `x == y` as discussed at https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior

**Comment by tfmorris** [comment]
LGTM (I apparently don't have rights to assign myself as a real Github reviewer)

**Pull request merged**
