### PR TITLE
Python 3 improvements

### PR DESCRIPTION
**Pull request by cclauss**
@mekarpeles @hornc @tfmorris  See #4

### CODE REVIEW

**Comment by cclauss** [comment]
Bump on this one.  118 days until Python 2 EOL.

**Comment by tfmorris** [comment]
The changes look fine by inspection, as far as they go, but they're insufficient to even get the module to load under Python 3 (httplib & StringIO imports need to be fixed up, at least).

Before we invest additional time, is this actually used anywhere? There's a reference on the linked issue to a PHP module, but I was unaware that OpenLibrary contains any PHP and I can't find any reference to acs4 in the source tree.

Also, since there are no tests for this, it's going to be pretty hard to make sure we've got it right.

**Comment by tfmorris** [comment]
OK, it's actually used here: 

https://github.com/internetarchive/openlibrary/blob/ce208e07eff8e5a6ddadecdc8534fbc570c2307a/openlibrary/core/lending.py#L19

`from openlibrary.plugins.upstream import acs4`

where openlibrary.plugins.upstream.acs4 is a symlink to our vendored acs4_py

I'll add the changes for the other two imports and see how much further that gets us.

**Comment by cclauss** [comment]
The OpenLibrary Travis test (when run on Python 3 _only_) should upgrade the symlink automagically.

**Comment by cclauss** [comment]
Closing in favor of #5

**Pull request closed without merging**
